services:
  - type: web
    name: n8n-service
    env: docker
    plan: free
    dockerfilePath: ./n8n.Dockerfile
    envVars:
      - key: N8N_HOST
        value: n8n-service.onrender.com
      - key: WEBHOOK_URL
        value: https://n8n-service.onrender.com/
      - key: N8N_ENCRYPTION_KEY
        value: bjay_secure_key_2026

  - type: web
    name: evolution-api
    env: docker
    plan: free
    dockerfilePath: ./evolution.Dockerfile
    envVars:
      - key: AUTHENTICATION_API_KEY
        value: 123456
      - key: DATABASE_ENABLED
        value: "true"
      - key: DATABASE_CONNECTION_URI
        value: "postgresql://bjay:axyUxIkyBo3eAcjcJCW8vexsfu6R8KiR@dpg-d7r6e2m7r5hc7397ajhg-a/evolution_h4r9"
      - key: DATABASE_CONNECTION_CLIENT_NAME
        value: "evolution_api"
      - key: CACHE_REDIS_ENABLED
        value: "false"
      - key: CACHE_LOCAL_ENABLED
        value: "true"