services:
  - type: web
    name: n8n-service
    env: docker
    plan: free
    dockerfilePath: ./n8n.Dockerfile
    envVars:
      - key: N8N_HOST
        value: n8n-service.onrender.com
      - key: WEBHOOK_URL
        value: https://n8n-service.onrender.com/
      - key: N8N_ENCRYPTION_KEY
        value: bjay_secure_key_2026

  - type: web
    name: evolution-api
    env: docker
    plan: free
    dockerfilePath: ./evolution.Dockerfile
    envVars:
      - key: AUTHENTICATION_API_KEY
        value: 123456
      - key: DATABASE_ENABLED
        value: "true"
      - key: DATABASE_PROVIDER
        value: postgresql
      - key: DATABASE_CONNECTION_URI
        value: "postgresql://automation_db_33ck_user:hW7AJrzQuvBE3Ox2eleuajlsR3lbaQh5@dpg-d8ults3tqb8s73be5u20-a/automation_db_33ck"
      - key: DATABASE_CONNECTION_CLIENT_NAME
        value: "evolution_api"
      - key: DATABASE_SAVE_DATA_INSTANCE
        value: "true"
      - key: CACHE_REDIS_ENABLED
        value: "false"
      - key: CACHE_LOCAL_ENABLED
        value: "true"
